spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin
server:
  port: 8090