spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5431/orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8060

application:
  config:
    customerUrl: http://localhost:8222/api/v1/customers
    productUrl: http://localhost:8222/api/v1/products
    paymentUrl: http://localhost:8222/api/v1/payments