spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5430/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8030